import Layout from "./components/Layout";
import "./globals.css";

export const metadata = {
  title: "Demo Phụ Kiện",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
        />
        {/* bootstrap 5 */}
        <link rel="stylesheet" href="/assets/css/lib/bootstrap.min.css" />
        {/* ====== font family ====== */}
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="/assets/css/lib/all.min.css" />
        <link rel="stylesheet" href="/assets/css/lib/animate.css" />
        <link rel="stylesheet" href="/assets/css/lib/jquery-ui.min.css" />
        <link rel="stylesheet" href="/assets/css/lib/jquery.fancybox.css" />
        <link rel="stylesheet" href="/assets/css/lib/lity.css" />
        <link rel="stylesheet" href="/assets/css/lib/swiper.min.css" />
        {/* ====== global style ====== */}
        <link rel="stylesheet" href="/assets/css/style.css" />
      </head>

      <body suppressHydrationWarning={true}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
